import {
  Home, Search, Bell, Sun, Moon, RefreshCw, Pause, Play, Filter, Plus,
  ChevronDown, ChevronRight, ChevronLeft, X, Copy, ExternalLink, Check,
  AlertTriangle, Clock, Activity, Send, ArrowUp, ArrowDown, ArrowRight,
  Sparkles, RotateCcw, XCircle, Code, User, Hash, Tag as TagIcon, Target,
  Box, Store, GitCompareArrows, LineChart, TrendingUp, TrendingDown, Webhook,
  KeyRound, Shield, Globe, Image as ImageIcon, FileText, Eye, EyeOff, Wrench,
  Brain, Briefcase, Folder, Mail, Lock, ScanLine, Layers, Inbox, Heart,
  type LucideIcon,
} from 'lucide-react';

/**
 * Icon map keyed by the prototype's names (ui.jsx `I`). Backed by lucide-react
 * (the prototype's icons were "lucide-style"), keeping the screen code identical
 * to the prototype's `<I.Xxx />` call sites. Default stroke width 1.75 matches the
 * prototype; pass `size` to override the 16px default.
 */
export const I = {
  Logo: TrendingUp,
  Home,
  Runs: Layers,
  Settings: Wrench,
  Search,
  Bell,
  Sun,
  Moon,
  Refresh: RefreshCw,
  Pause,
  Play,
  Filter,
  Plus,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  X,
  Copy,
  External: ExternalLink,
  Check,
  AlertTriangle,
  Clock,
  Activity,
  Send,
  ArrowUp,
  ArrowDown,
  ArrowRight,
  Sparkle: Sparkles,
  Replay: RotateCcw,
  Cancel: XCircle,
  Code,
  User,
  Hash,
  Tag: TagIcon,
  Target,
  Box,
  Store,
  Compare: GitCompareArrows,
  Chart: LineChart,
  TrendUp: TrendingUp,
  TrendDown: TrendingDown,
  Anomaly: Activity,
  AI: Brain,
  Webhook,
  Key: KeyRound,
  Shield,
  Globe,
  Image: ImageIcon,
  FileText,
  Eye,
  EyeOff,
  Wrench,
  Brain,
  Briefcase,
  Folder,
  Mail,
  Lock,
  ScanLine,
  Layers,
  Inbox,
  Heart,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof I;
export const ICON_STROKE = 1.75;
export const ICON_SIZE = 16;
